# Theme settings
dox:
    baseurl:
    title: PhotographyResources.io
    theme_color: '#0976f8' # Define theme primary color with HEX value
    language: en-US # Use ISO language and country codes to setup language of your website - https://www.w3schools.com/tags/ref_language_codes.asp and https://www.w3schools.com/tags/ref_country_codes.asp
    header:
        logo:
            text: PhotographyResources.io
            image:
        nav:
            # - item_name: Homepage
            #   item_url: /
            - item_name: About
              item_url: /about
        cta:
            label: Newsletter
            url: /documentation
            icon:  # Choose from 266 icons in "Feather" icon set, list of all icons is available here - https://feathericons.com
    footer:
        logo:
            text: the best camera is the one we always have
            image:
        text: Made with ☕️ from 🇳🇴 and 🇨🇦
    google_analytics:
        tracking_code: UA-58630348-9 
    hotjar:
        enabed: yesir # leave blank is hotjar is not enabled through hotjar.com
    comments:
        disqus_forum_shortname: # Add your Disqus forum shortname to activate comments site-wide

# Defining collections
collections:
    documentation:
        output: true

# Defining defaults
defaults:
    -
        scope:
            path: ''
            type: 'documentation'
        values:
            layout: 'documentation-single'

# SASS settings
sass:
    sass_dir: ./troll-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./troll-theme/_layouts
includes_dir: ./troll-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/
